Adds virtual deploy Jenkins verify with gerrit trigger for Foreman
JJB updated to now trigger foreman virtual deploy on patchsets.  This is
needed to verify proposed patches correctly.  Currently will run on
opnfv-jump-2 and is disabled, but will move to correct POD when provided
by LF lab and enable.

JIRA: OCTO-99

Change-Id: I2516a87ac2a292bbd1678ba1ae8dadeaca5017ac
Signed-off-by: Tim Rozet <trozet@redhat.com>

diff --git a/jjb/genesis/genesis-foreman.yml b/jjb/genesis/genesis-foreman.yml
--- a/jjb/genesis/genesis-foreman.yml
+++ b/jjb/genesis/genesis-foreman.yml
@@ -15,6 +15,7 @@
         - 'genesis-foreman-daily-{stream}'
         - 'genesis-foreman-build-{stream}'
         - 'genesis-foreman-deploy-{stream}'
+        - 'genesis-foreman-deploy-virtual-{stream}'
 
     # stream:    branch with - in place of / (eg. stable-arno)
     # branch:    branch (eg. stable/arno)
@@ -94,6 +95,7 @@
     builders:
         - 'foreman-build'
         - 'foreman-workspace-cleanup'
+        - 'foreman-deploy-virtual'
 
 - job-template:
     name: 'genesis-foreman-merge'
@@ -266,6 +268,41 @@
     builders:
         - 'foreman-deploy'
 
+- job-template:
+    name: 'genesis-foreman-deploy-virtual-{stream}'
+
+    project-type: freestyle
+
+    disabled: true
+
+    node: opnfv-jump-2
+
+    logrotate:
+        daysToKeep: 30
+        numToKeep: 10
+        artifactDaysToKeep: -1
+        artifactNumToKeep: -1
+
+    parameters:
+        - project-parameter:
+            project: '{project}'
+        - foreman-parameter:
+            installer: '{installer}'
+            gs-pathname: '{gs-pathname}'
+        - string:
+            name: GIT_BASE
+            default: ssh://gerrit.opnfv.org:29418/$PROJECT
+            description: "Used for overriding the GIT URL coming from parameters macro."
+
+    scm:
+        - git-scm:
+            credentials-id: '{ssh-credentials}'
+            refspec: ''
+            branch: '{branch}'
+
+    builders:
+        - 'foreman-deploy-virtual'
+
 ########################
 # parameter macros
 ########################
@@ -356,6 +393,33 @@
 
             # and then initiate deployment
             sudo $WORKSPACE/$INSTALLER/ci/deploy.sh -base_config $WORKSPACE/$INSTALLER/ci/inventory/lf_pod2_ksgen_settings.yml
+
+            echo
+            echo "--------------------------------------------------------"
+            echo "Done!"
+
+- builder:
+    name: 'foreman-deploy-virtual'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set -o errexit
+            set -o nounset
+            set -o pipefail
+
+            # log info to console
+            echo "Starting the virtual deployment using $INSTALLER. This could take some time..."
+            echo "--------------------------------------------------------"
+            echo
+
+            # cleanup baremetal first (in case baremetal was being used on pod2, remove when moved to isolated Virtual pod)
+            sudo $WORKSPACE/$INSTALLER/ci/clean.sh -base_config $WORKSPACE/$INSTALLER/ci/inventory/lf_pod2_ksgen_settings.yml
+
+            # cleanup virtual
+            sudo $WORKSPACE/$INSTALLER/ci/clean.sh -virtual
+
+            # and then initiate deployment
+            sudo $WORKSPACE/$INSTALLER/ci/deploy.sh -virtual
 
             echo
             echo "--------------------------------------------------------"
