Adds lab reconfig to JJB for Foreman
Adds another builder to do the lab reconfig pulls in UCS
login info from the local jumphost.  Need to still
add the updates for Fuel, but want to make sure these changes are good.

JIRA: OCTO-109

Change-Id: I8e7988b49e8ae44b37973472deff800b9f4f21e8
Signed-off-by: Tim Rozet <trozet@redhat.com>

diff --git a/jjb/genesis/genesis-foreman.yml b/jjb/genesis/genesis-foreman.yml
--- a/jjb/genesis/genesis-foreman.yml
+++ b/jjb/genesis/genesis-foreman.yml
@@ -264,6 +264,7 @@
             branch: '{branch}'
 
     builders:
+        - 'foreman-lab-reconfig'
         - 'foreman-deploy'
 
 ########################
@@ -296,6 +297,46 @@
 ########################
 # builder macros
 ########################
+- builder:
+    name: 'foreman-lab-reconfig'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set -o errexit
+            set -o nounset
+            set -o pipefail
+
+            # check to see if ucs login info file exists
+            if [ -e /home/jenkins-ci/.ssh/ucs_creds ];then
+              source /home/jenkins-ci/.ssh/ucs_creds
+            else
+              echo "Unable to find UCS credentials for LF lab reconfiguration...Exiting"
+              exit 1
+            fi
+
+            # clone releng
+            echo "Cloning releng repo..."
+            if ! GIT_SSL_NO_VERIFY=true git clone https://gerrit.opnfv.org/gerrit/releng; then
+              echo "Unable to clone releng repo...Exiting"
+              exit 1
+            fi
+
+            # log info to console
+            echo "Starting the lab reconfiguration for $INSTALLER..."
+            echo "--------------------------------------------------------"
+            echo
+
+            # create venv
+            sudo $WORKSPACE/releng/utils/lab-reconfiguration/create_venv.sh
+
+            # enter venv
+            source ./venv/bin/activate
+            sudo python $WORKSPACE/releng/utils/lab-reconfiguration/reconfigUcsNet.py $ucs_host -u $ucs_user -p $ucs_password -f $WORKSPACE/releng/utils/lab-reconfiguration/foreman.yaml
+
+            echo
+            echo "--------------------------------------------------------"
+            echo "Done!"
+
 - builder:
     name: 'foreman-build'
     builders:
