Inclusion of dhrystone benchmark jenkings jobs for QTIP
Two jenkings jobs added for the Dell lab.
Jobs would run dhrystone benchmarks.
1st Job: dhrystone on Baremetal vs VM
2nd Job: dhrysotne on Baremetal vs Baremetal
Previous commit reverted as it successfully verified but failed to merge

JIRA: QTIP-7

Change-Id: I2522602e931b1d1f3d7e68fcb1df6268e7510220
Signed-off-by: Nauman Ahad <Nauman_Ahad@dell.com>

diff --git a/jjb/qtip/qtip.yml b/jjb/qtip/qtip.yml
--- a/jjb/qtip/qtip.yml
+++ b/jjb/qtip/qtip.yml
@@ -5,9 +5,21 @@
         - 'qtip-daily-{stream}'
         - 'qtip-merge'
         - 'qtip-verify'
+        - 'qtip-dhrystone-VM_vs_Baremetal-{pod}'
+        - 'qtip_dhrystone-BM_vs_BM-{pod}'
+
 
     # stream:    branch with - in place of / (eg. stable-helium)
     # branch:    branch (eg. stable/helium)
+
+
+    pod:
+        - dell-build:
+           node: 'dell-build'
+           installer_type: 'foreman'
+           installer_ip: '172.18.0.12'
+
+
     stream:
         - master:
             branch: 'master'
@@ -51,6 +63,7 @@
     parameters:
         - project-parameter:
             project: '{project}'
+
 
     scm:
         - git-scm:
@@ -177,3 +190,136 @@
             pwd
             find .
             echo "merge logic goes here"
+
+- job-template:
+    name: 'qtip-dhrystone-VM_vs_Baremetal-{pod}'
+
+    project-type: freestyle
+
+    disabled: false
+
+    node: '{node}'
+
+    logrotate:
+      daysToKeep: 30
+      numToKeep: 10
+      artifactDaysToKeep: -1
+      artifactNumToKeep: -1
+
+    parameters:
+      - project-parameter:
+          project: '{project}'
+      - string:
+          name: INSTALLER_TYPE
+          default: '{installer_type}'
+          description: "Installer name that is used for deployment."
+      - string:
+          name: INSTALLER_IP
+          default: '{installer_ip}'
+          description: "Installer IP"
+      - string:
+          name: GIT_BASE
+          default: https://gerrit.opnfv.org/gerrit/$PROJECT
+          description: "Used for overriding the GIT URL coming from Global Jenkins configuration in case if the stuff is done on none-LF HW."
+
+    scm:
+       - git-scm:
+           credentials-id: '{ssh-credentials}'
+           refspec: ''
+           branch: master
+
+    builders:
+        - 'qtip-fetch-os-cred'
+        - 'qtip-dhrystone-VM_vs_BM'
+
+- job-template:
+    name: 'qtip_dhrystone-BM_vs_BM-{pod}'
+
+
+    project-type: freestyle
+
+    disabled: false
+
+    node: '{node}'
+
+    logrotate:
+      daysToKeep: 30
+      numToKeep: 10
+      artifactDaysToKeep: -1
+      artifactNumToKeep: -1
+
+    parameters:
+      - project-parameter:
+          project: '{project}'
+      - string:
+          name: INSTALLER_TYPE
+          default: '{installer_type}'
+          description: "Installer name that is used for deployment."
+      - string:
+          name: INSTALLER_IP
+          default: '{installer_ip}'
+          description: "IP address of the installer"
+      - string:
+          name: GIT_BASE
+          default: https://gerrit.opnfv.org/gerrit/$PROJECT
+          description: "Used for overriding the GIT URL coming from Global Jenkins configuration in case if the stuff is done on none-LF HW."
+
+    scm:
+       - git-scm:
+           credentials-id: '{ssh-credentials}'
+           refspec: ''
+           branch: master
+
+    builders:
+      - 'qtip-fetch-os-cred'
+      - 'qtip-dhrystone-BM_vs_BM'
+
+
+###########################
+#biuilder macros
+###########################
+- builder:
+    name: qtip-dhrystone-VM_vs_BM
+
+    builders:
+        - shell: |
+            #! /bin/bash
+
+
+            if [[ ! -f $HOME/opnfv-openrc.sh]]; then
+               echo "Unable to access file $HOME/opnfv-openrc.sh"
+               exit 1
+            fi
+            source $HOME/opnfv-openrc.sh
+            cd $WORKSPACE
+
+
+            echo "Running QTIP dhrystone with First Test case"
+            ./QTIP.sh First dhrystone
+
+
+- builder:
+    name: qtip-dhrystone-BM_vs_BM
+
+    builders:
+        - shell: |
+            #!/bin/bash
+
+
+            if [[ ! -f $HOME/opnfv-openrc.sh]]; then
+               echo "Unable to access file $HOME/opnfv-openrc.sh"
+               exit 1
+            fi
+            source $HOME/opnfv-openrc.sh
+            cd $WORKSPACE
+
+
+            echo "Running QTIP dhrystone with Second Test case"
+            ./QTIP.sh Second dhrystone
+
+
+- builder:
+    name: qtip-fetch-os-cred
+    builders:
+        - shell: |
+            !include-raw ../../utils/fetch_os_creds.sh
