Revert "remove sourcing of opnfv-openrc.rc in releng script"
This reverts commit dae21e80b2a8a9b8201abd2aeaa082be970eb6ca.

diff --git a/jjb/functest/functest.yml b/jjb/functest/functest.yml
--- a/jjb/functest/functest.yml
+++ b/jjb/functest/functest.yml
@@ -70,6 +70,12 @@
 
             echo "Functest: prepare Functest environment"
             mkdir -p $HOME/functest/
+            # source openstack vars
+            if [[ ! -f $HOME/opnfv-openrc.sh ]]; then
+                echo "Unable to access file $HOME/opnfv-openrc.sh"
+                exit 1
+            fi
+            source $HOME/opnfv-openrc.sh
 
             # WORKSPACE is the root of the functest repo
             # go into WORKSPACE where the functest repo is cloned
@@ -130,6 +136,12 @@
 
             echo "Functest: prepare Functest environment"
             mkdir -p $HOME/functest/
+            # source openstack vars
+            if [[ ! -f $HOME/opnfv-openrc.sh ]]; then
+                echo "Unable to access file $HOME/opnfv-openrc.sh"
+                exit 1
+            fi
+            source $HOME/opnfv-openrc.sh
 
             # WORKSPACE is the root of the functest repo
             # go into WORKSPACE where the functest repo is cloned
@@ -564,6 +576,7 @@
 
             echo "Functest: prepare Functest environment"
             mkdir -p $HOME/functest/
+            source $HOME/functest/opnfv-openrc.sh
 
             # WORKSPACE is the root of the functest repo
             # go into WORKSPACE where the functest repo is cloned
