Update vIMS jobs
JIRA: FUNCTEST-38

Change-Id: I6fc3294fe81f4c04bab03f45f8ead845f2c4e345
Signed-off-by: boucherv <valentin.boucher@orange.com>

diff --git a/jjb/functest/functest.yml b/jjb/functest/functest.yml
--- a/jjb/functest/functest.yml
+++ b/jjb/functest/functest.yml
@@ -29,7 +29,7 @@
         - 'functest-openstack-bench-test-{pod}'
         - 'functest-openstack-tempest-smoke-test-{pod}'
         - 'functest-odl-test-{pod}'
-        - 'functest-vims-test-{installer}-{stream}'
+        - 'functest-vims-{installer}-{stream}'
         - 'functest-vping-test-{pod}'
         - 'functest-daily-{stream}'
         - 'functest-merge-{stream}'
@@ -252,28 +252,6 @@
             $WORKSPACE/testcases/Controllers/ODL/CI/start_tests.sh
 
 - job-template:
-    name: functest-vims-test-{installer}-{stream}
-
-    project-type: freestyle
-
-    node: '{pod}'
-
-    logrotate:
-        daysToKeep: 30
-        numToKeep: 10
-        artifactDaysToKeep: -1
-        artifactNumToKeep: -1
-
-    builders:
-        - shell: |
-            #!/bin/bash
-            set +e
-            # vIMS
-            echo "Functest: run vIMS"
-            python $WORKSPACE/testcases/vIMS/CI/vIMS.py --debug $WORKSPACE/
-
-
-- job-template:
     name: functest-vping-test-{pod}
 
     project-type: freestyle
@@ -373,6 +351,45 @@
         - 'functest-all'
         - 'functest-store-results'
         - 'functest-cleanup'
+
+- job-template:
+    name: functest-vims-{installer}-{stream}
+
+    project-type: freestyle
+
+    node: '{node}'
+
+    parameters:
+        - project-parameter:
+            project: '{project}'
+        - string:
+            name: INSTALLER_TYPE
+            default: '{installer_type}'
+            description: "Installer name that is used for deployment."
+        - string:
+            name: INSTALLER_IP
+            default: '{installer_ip}'
+            description: "Installer IP."
+        - string:
+            name: GIT_BASE
+            default: ssh://gerrit.opnfv.org:29418/$PROJECT
+            description: "Override GIT_BASE"
+
+    scm:
+        - git-scm:
+            credentials-id: '{ssh-credentials}'
+            refspec: ''
+            branch: master
+
+    logrotate:
+        daysToKeep: 30
+        numToKeep: 10
+        artifactDaysToKeep: -1
+        artifactNumToKeep: -1
+
+    builders:
+        - 'functest-fetch-os-creds'
+        - 'functest-vims'
 
 - job-template:
     name: 'functest-daily-{stream}'
@@ -646,6 +663,30 @@
 
             # save tempest.conf for further troubleshooting
             cp $HOME/.rally/tempest/for-deployment-*/tempest.conf $HOME/functest/results
+
+- builder:
+    name: functest-vims
+    builders:
+        - shell: |
+            #!/bin/bash
+            set +e
+
+            # source openstack vars
+            if [ ! -f $HOME/opnfv-openrc.sh ]; then
+                echo "Credentials file not found in "$HOME/opnfv-openrc.sh
+                exit 1
+            fi
+            echo "Sourcing the OpenStack credentials in"$HOME/opnfv-openrc.sh
+            source $HOME/opnfv-openrc.sh
+
+            # WORKSPACE is the root of the functest repo
+            # go into WORKSPACE where the functest repo is cloned
+            cd $WORKSPACE
+
+            # vIMS
+            echo "Functest: run vIMS"
+            python $WORKSPACE/testcases/vIMS/CI/vIMS.py --debug $WORKSPACE/
+
 
 - builder:
     name: functest-store-results
