adding the apex virtual deploy job
Change-Id: I8e547ed70e486006e3db07768572de577e0daa12
Signed-off-by: Dan Radez <dradez@redhat.com>

diff --git a/jjb/apex/apex.yml b/jjb/apex/apex.yml
--- a/jjb/apex/apex.yml
+++ b/jjb/apex/apex.yml
@@ -189,6 +189,77 @@
         - 'apex-upload-artifact'
         - 'apex-workspace-cleanup'
 
+- job-template:
+    name: 'apex-verify-deploy-virtual-{stream}'
+
+    project-type: freestyle
+
+    node: opnfv-jump-1
+
+    logrotate:
+        daysToKeep: 30
+        numToKeep: 10
+        artifactDaysToKeep: -1
+        artifactNumToKeep: -1
+
+    parameters:
+        - project-parameter:
+            project: '{project}'
+        - gerrit-parameter:
+            branch: '{branch}'
+        - string:
+            name: GIT_BASE
+            default: ssh://gerrit.opnfv.org:29418/$PROJECT
+            description: "Used for overriding the GIT URL coming from parameters macro."
+
+    wrappers:
+        - ssh-agent-credentials:
+            user: '{ssh-credentials}'
+
+    triggers:
+        - gerrit:
+            trigger-on:
+                - patchset-created-event:
+                    exclude-drafts: 'false'
+                    exclude-trivial-rebase: 'false'
+                    exclude-no-code-change: 'false'
+                - draft-published-event
+                - comment-added-contains-event:
+                    comment-contains-value: 'recheck'
+                - comment-added-contains-event:
+                    comment-contains-value: 'reverify'
+            projects:
+              - project-compare-type: 'ANT'
+                project-pattern: 'genesis'
+                branches:
+                  - branch-compare-type: 'ANT'
+                    branch-pattern: '**/{branch}'
+                file-paths:
+                  - compare-type: ANT
+                    pattern: 'common/ci/**'
+                  - compare-type: ANT
+                    pattern: 'common/manifests/**'
+                  - compare-type: ANT
+                    pattern: 'common/puppet-opnfv/**'
+                  - compare-type: ANT
+                    pattern: 'common/tools/**'
+                  - compare-type: ANT
+                    pattern: '{installer}/build/**'
+                  - compare-type: ANT
+                    pattern: '{installer}/ci/**'
+                  - compare-type: ANT
+                    pattern: '{installer}/include/**'
+                forbidden-file-paths:
+                  - compare-type: ANT
+                    pattern: 'common/docs/**'
+                  - compare-type: ANT
+                    pattern: '{installer}/docs/**'
+            dependency-jobs: 'apex-verify-{stream}'
+
+
+    builders:
+        - 'apex-deploy-virtual'
+
 ########################
 # parameter macros
 ########################
@@ -299,6 +370,45 @@
             echo "Done!"
             echo "ISO Artifact is available as http://$GS_URL/opnfv-$OPNFV_ARTIFACT_VERSION.iso"
             echo "RPM Artifact is available as http://$GS_URL/$(basename $OPNFV_RPM_URL)"
+
+- builder:
+    name: 'apex-deploy-virtual'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set -o errexit
+            set -o nounset
+            set -o pipefail
+
+            # log info to console
+            echo "Starting the Apex virtual deployment."
+            echo "--------------------------------------------------------"
+            echo
+
+            # get the latest.properties file in order to get info regarding latest artifact
+            curl -s -o $WORKSPACE/opnfv.properties http://$GS_URL/latest.properties
+
+            # check if we got the file
+            [[ -f opnfv.properties ]] || exit 1
+
+            # source the file so we get OPNFV vars
+            source opnfv.properties
+
+            # update / install the new rpm
+            if rpm -q opnfv-apex; then
+               sudo yum update -y $RPM_URL;
+            else
+               sudo yum install -y $RPM_URL;
+            fi
+
+            # cleanup virtual machines before we start
+            sudo sudo opnfv-clean
+            # initiate virtual deployment
+            sudo opnfv-deploy -v
+
+            echo
+            echo "--------------------------------------------------------"
+            echo "Done!"
 
 
 #######################
