apex: Add dependency for python34-PyYAML for verify
Change-Id: I412f57456d5dd8c34c90525f6066831351489aec
Signed-off-by: Feng Pan <fpan@redhat.com>

diff --git a/jjb/apex/apex.yml b/jjb/apex/apex.yml
--- a/jjb/apex/apex.yml
+++ b/jjb/apex/apex.yml
@@ -855,6 +855,13 @@
                         exit 1
                     fi
                 fi
+                if ! rpm -q python34-PyYAML > /dev/null; then
+                    sudo yum install -y epel-release
+                    if ! sudo yum install -y python34-PyYAML; then
+                        echo "Failed to install python34-PyYAML"
+                        exit 1
+                    fi
+                fi
                 if [ -z ${PYTHONPATH:-} ]; then
                     export PYTHONPATH=${WORKSPACE}/lib/python
                 else
