Install python34-setuptools for verify job
This package is required for installing jinja2 python package with
easy_install-3.4 tool.

Change-Id: I8df9667d5c435b179d5b5af8a8881bb50704dd49
Signed-off-by: Feng Pan <fpan@redhat.com>

diff --git a/jjb/apex/apex.yml b/jjb/apex/apex.yml
--- a/jjb/apex/apex.yml
+++ b/jjb/apex/apex.yml
@@ -917,6 +917,12 @@
                         exit 1
                     fi
                 fi
+                if ! rpm -q python34-setuptools > /dev/null; then
+                    if ! sudo yum install -y python34-setuptools; then
+                        echo "Failed to install python34-setuptools"
+                        exit 1
+                    fi
+                fi
                 if [ -z ${PYTHONPATH:-} ]; then
                     export PYTHONPATH=${WORKSPACE}/lib/python
                 else
