[functest] run vping test as smoke test after the baremetal deployment
JIRA: COMPASS-165

Change-Id: I38444a86af3898c4515e503f47e173031e513d1a
Signed-off-by: meimei <meimei@huawei.com>

diff --git a/jjb/compass4nfv/compass4nfv.yml b/jjb/compass4nfv/compass4nfv.yml
--- a/jjb/compass4nfv/compass4nfv.yml
+++ b/jjb/compass4nfv/compass4nfv.yml
@@ -382,6 +382,10 @@
         - 'builder-compass-ci-preclean-workspace'
         - 'builder-compass-download-artifact'
         - 'builder-compass-deploy-bare'
+        - 'builder-set-functest-env'
+        - 'builder-functest-vping'
+        - 'builder-functest-cleanup'
+
 
     publishers:
         - archive:
@@ -412,6 +416,10 @@
             name: GIT_BASE
             default: https://gerrit.opnfv.org/gerrit/$PROJECT
             description: "Used for overriding the GIT URL coming from Global Jenkins configuration in case if the stuff is done on none-LF HW."
+        - string:
+            name: FUNCTEST_REPO_DIR
+            default: '/home/opnfv/repos/functest'
+            description: "Directory where the root functest repo is cloned in the docker."
         - string:
             name: GS_URL
             default: artifacts.opnfv.org/$PROJECT/
@@ -658,4 +666,64 @@
             cd $WORKSPACE/..
             sudo rm $WORKSPACE -rf
             git clone $GIT_BASE  $WORKSPACE
+
+- builder:
+    name: 'builder-set-functest-env'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set +e
+
+            echo "Functest: Start Docker and prepare environment"
+            envs="INSTALLER_TYPE=${INSTALLER} -e INSTALLER_IP=${installer_ip}"
+            docker ps -a | grep opnfv/functest | awk '{print $1}' | xargs docker rm -f &>/dev/null
+            docker pull opnfv/functest
+            echo "Functest: Running docker run command: docker run -i -e $envs opnfv/functest /bin/bash &"
+            docker run -i -e $envs opnfv/functest /bin/bash &
+            docker ps -a
+            sleep 5
+            container_id=$(docker ps -a | grep opnfv/functest | awk '{print $1}' | head -1)
+            echo "Container ID=${container_id}"
+            if [ -z ${container_id} ]; then
+                echo "Cannot find opnfv/functest container ID ${container_id}. Please check if it is existing."
+                docker ps -a
+                exit 1
+            fi
+            echo "Starting the container: docker start ${container_id}"
+            docker start ${container_id}
+            sleep 5
+            docker ps
+            if [ $(docker ps | grep opnfv/functest | wc -l) == 0 ]; then
+                echo "The container opnfv/functest with ID=${container_id} has not been properly started. Exiting..."
+                exit 1
+            fi
+            cmd="${FUNCTEST_REPO_DIR}/docker/prepare_env.sh"
+            echo "Executing command inside the docker: ${cmd}"
+            docker exec ${container_id} ${cmd}
+
+- builder:
+    name: 'builder-functest-vping'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set +e
+
+            echo "Functest: run vPing"
+            cmd="${FUNCTEST_REPO_DIR}/docker/run_tests.sh --test vping"
+            container_id=$(docker ps -a | grep opnfv/functest | awk '{print $1}' | head -1)
+            docker exec $container_id $cmd
+
+- builder:
+    name: 'builder-functest-cleanup'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set +e
+
+            # cleanup: remove any docker containers leftovers
+            echo "Removing the docker container..."
+            docker rm -f $(docker ps | grep opnfv/functest | awk '{print $1}')
+            echo "Removing the docker image..."
+            docker rmi -f $(docker images | grep opnfv/functest | awk '{print $3}')
+
 
