Add the tox pep8 check in parser verify
JIRA:RELENG-110

Change-Id: I5c877d558bb04255a9e99dbe3459fba40217232c
Signed-off-by: zhifeng.jiang <jiang.zhifeng@zte.com.cn>

diff --git a/jjb/parser/parser.yml b/jjb/parser/parser.yml
--- a/jjb/parser/parser.yml
+++ b/jjb/parser/parser.yml
@@ -58,4 +58,33 @@
 
     builders:
         - shell: |
-            echo "Nothing to verify!"
+            #/bin/bash
+            set -o errexit
+            set -o pipefail
+            set -o xtrace
+            export PATH=$PATH:/usr/local/bin/
+            
+            virtualenv -p python2.7 $WORKSPACE/parser_tox
+            source $WORKSPACE/parser_tox/bin/activate
+            
+            #install python packages tox
+            pip install tox
+            
+            run_PEP8() {
+                tox -e pep8 
+                if [ $? -ne 0 ]; then
+                   echo "FAILED"
+                   exit 1
+                else
+                   echo "OK"
+                fi
+            }
+
+            # pep8 check parser/tosca2heat/tosca-parser
+            echo "Running tox -e pep8 on tosca2heat ..."
+            cd $WORKSPACE/parser/tosca2heat/tosca-parser
+            run_PEP8
+            cd $WORKSPACE/parser/tosca2heat/heat-translator
+            run_PEP8
+
+            deactivate
